### ISSUE TITLE
z3 never terminated

### ISSUE THREAD

**Issue by aommm** [danr/emna#1]
OSX 10.10.5
Z3 version 4.4.0

When I invoke for example

```
dist/build/emna/emna --prover=z examples/Reverse.hs
```

emna proves the property properly and exits, but z3 continues running in the background eating up CPU until killed.

**Comment by danr** [comment]
I just pushed a commit which make z3 time itself out, do you still have this problem?

**Comment by aommm** [comment]
Seems to have been fixed, works perfectly so far!
