### ISSUE TITLE
Proof failure not reported correctly

### ISSUE THREAD

**Issue by aommm** [danr/emna#3]
For `isaplanner/prop_06.smt2` (and others): the property cannot be proven, but summary of proof is still printed, and exit code is 0.

Some debugging info:
 `loop` returns `Right` when it shouldn't, from [line 135](https://github.com/danr/emna/blob/master/Main.hs#L135).
The reason for this is that there is no `UserAsserted` property left in the list. All the remaining properties have `fm_info = Unknown` (which I think means "conjectured by QuickSpec").
This means that the original `UserAsserted` property disappears along the way somehow.

**Comment by danr** [comment]
This is really bad. I won't have time to look at it until Friday unfortunately.

**Comment by aommm** [comment]
Still a problem with [latest emna](https://github.com/danr/emna#1e0a0dce8fa92fd92937cab532a7d0f39f4bae50) and [latest tip-tools](https://github.com/tip-org/tools#407630d34e678956b8f8b66c5713e570f2fbcb66).
More specifically, running `emna --prover=z  ~/tip-benchmarks/benchmarks/prod/prop_21.smt2` gives both the output "Failed to prove" and the exit status code 0.
